### ISSUE TITLE
StPlayground raises ED

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/NewTools#102]
When we resize it. 

![Screenshot 2020-08-26 at 11 30 21](https://user-images.githubusercontent.com/432549/91287152-a141b900-e78f-11ea-8d4a-bd858b3b2309.png)

**Comment by Ducasse** [comment]
![Screenshot 2020-08-26 at 11 32 32](https://user-images.githubusercontent.com/432549/91287316-dbab5600-e78f-11ea-9f68-6bf65b1e2b54.png)

**Comment by MarcusDenker** [comment]
This is fixed I think (I can not reproduce)
