### ISSUE TITLE
SindarinBytecodeToASTCache should not be used anymore

### ISSUE THREAD

**Issue by MarcusDenker** [pharo-spec/NewTools#107]
SindarinBytecodeToASTCache should not be used anymore

We have integrated the code in Pharo and there where lots of bug fixes...

See OCBytecodeToASTCache

I added an issue here too: https://github.com/pharo-spec/ScriptableDebugger/issues/9

**Comment by MarcusDenker** [comment]
PR: https://github.com/pharo-spec/ScriptableDebugger/pull/11

**Comment by StevenCostiou** [comment]
Fixed by https://github.com/pharo-spec/ScriptableDebugger/pull/11
