### ISSUE TITLE
Evaluation within the debugger uses a wrong context

### ISSUE THREAD

**Issue by guillep** [pharo-spec/NewTools#112]
Doing a Cmd+D or Cmd+P in the debugger does not work properly.

For example, take the following code:
```smalltalk
1@2 -> 3
```

Debug it, step over `@` and into `->`

Now the debugger shows the method:

```smalltalk
-> anObject
	"Answer an Association between self and anObject"
	"The following example creates an association whose key is number 1 and value string 'one'."

	"(1 -> 'one') key >>> 1"
	"(1 -> 'one') value >>> 'one'"
	
	"Note that key and value can be ANY object."
	
	^Association key: self value: anObject
```

The debugger inspector shows correctly the that `self` is the point, and its `x` and `y` instance variables.

![image](https://user-images.githubusercontent.com/708322/94241984-b0925e80-ff15-11ea-870f-7ae91c89e815.png)

However, evaluating `x` and printing it yields what seem a compilation error.

![image](https://user-images.githubusercontent.com/708322/94242047-c56ef200-ff15-11ea-8032-ab0472afbc14.png)

Digging a bit further, it seems that the method of the evaluation is being compiled in the context of the class of the current method, instead of the class of the current receiver.

![image](https://user-images.githubusercontent.com/708322/94242152-e6374780-ff15-11ea-9688-bb65c56c5738.png)

To have a good debugger experience this should have been compiled in `Point`, otherwise evaluations cannot access instance variables of the current receiver if we are in a superclass method by chance...

**Comment by MarcusDenker** [comment]
This PR fixes the wrong class: https://github.com/pharo-project/pharo/pull/8136

**Comment by MarcusDenker** [comment]
PR was merged, works in both Pharo9 and with latest NewTools loaded
