### ISSUE TITLE
ByteString does not understand description when Stepping through

### ISSUE THREAD

**Issue by guillep** [pharo-spec/NewTools#113]
Debug the following

```smalltalk
RBParser parseFaultyMethod: 'toto

a b := 1'
```

Then
1. step into
2. over
3. into
4. over
5. over
6. over
7. over

![image](https://user-images.githubusercontent.com/708322/94244416-20eeaf00-ff19-11ea-89ce-f28681e031af.png)

8. step through
9. step through => Boom

**Comment by StevenCostiou** [comment]
This is under investigation, I have a fix ready (I think) but not pushed yet. Next week should be good.

**Comment by StevenCostiou** [comment]
Fixed in next NewTools merge.

**Comment by MarcusDenker** [comment]
This has been merged
