### ISSUE TITLE
Compiling methods with unknown Classes fails

### ISSUE THREAD

**Issue by guillep** [pharo-spec/NewTools#119]
Probably this is a duplicate, but since this is another case I'm not sure.

I'm programming in the debugger, and I write an expression that uses a class that does not exist yet.
Instead of proposing me to create the class I have a DNU.

**Comment by MarcusDenker** [comment]
I think this is the same problem that is fixed by the revert: https://github.com/pharo-project/pharo/pull/7452

**Comment by MarcusDenker** [comment]
This can be closed

**Comment by StevenCostiou** [comment]
Yes this is fixed now.
