### ISSUE TITLE
Debugger: ReturnValueDebugCommand accesses a #context variable

### ISSUE THREAD

**Issue by dupriezt** [pharo-spec/NewTools#12]
- Run in playground:
```
self halt.
a := Point x: 1 y:2.
Point new.
```
- Step into the call to #x:y:
- Use the Return button and type `context` as the expression to return.
- After this you should be in the DoIt context. Step over the assignment to the 'a' variable.
The value of the 'a' variable (the first value of the operand stack of thisContext) is the Point class.
However, there was no `context` variable in the context where we used the Return button, so the return value should have been nil (like it is when you type gibberish as expression to return) instead of the Point class.

**Comment by dupriezt** [comment]
My guess would be that this issue comes from this piece of ReturnValueDebugCommand>>#execute 
```Smalltalk
	value := self class compiler
			source: expression;
			context: self currentContext;
			receiver: self currentContext receiver;
			evaluate.
```
This compiler is that of the ReturnValueDebugCommand class, meaning it has access to its #context variable. This is probably why evaluating "context" with this compiler yields an actual result instead of nil.

**Comment by StevenCostiou** [comment]
This works now (with StPlayground).
