### ISSUE TITLE
[Debugger] Change focus in debugger loses code

### ISSUE THREAD

**Issue by guillep** [pharo-spec/NewTools#120]
I'm in the debugger
Change some code
Select another frame
=> my code is lost

**Comment by StevenCostiou** [comment]
@guillep what behaviour would you expect?
As this never worked before in GT (at least, the same bug exists in current GT), I am not sure what behaviour would be best. We could:
1. just show the other frame, and when we go back to the frame with the modified code show the modifications (but no impact until changes are saved) -> in that case we could show in the stack an indication of which frame is being edited
2. show a popup that asks if it is ok to cancel changes (that I do not like)
What do you think?

**Comment by StevenCostiou** [comment]
So it looks like that. Now, I just need to plug the cancel action (shortcut + menu) from the code presenter.
With some luck I can make it come with the next merge :)

![Screenshot 2020-10-14 at 18 59 51](https://user-images.githubusercontent.com/26929529/96021232-726ec780-0e4f-11eb-8a3e-90c3b96ad6bc.png)
