### ISSUE TITLE
Memory leaks?

### ISSUE THREAD

**Issue by guillep** [pharo-spec/NewTools#121]
I have an image that I'm using since 2 days, and it just became 5.3GB

![image](https://user-images.githubusercontent.com/708322/95601923-7e741700-0a54-11eb-841e-4819385efd33.png)

![image](https://user-images.githubusercontent.com/708322/95602021-a499b700-0a54-11eb-857c-5c9dd7321c58.png)

Every time I save the image its bigger and bigger

**Comment by StevenCostiou** [comment]
Could you tell how much of the `SpWindowPresenter` instances in `windows` are a debugger? There was a bug where debuggers were never GC'ed and I never knew if it was fixed or not.

**Comment by guillep** [comment]
All of them... I have the image if you want to take a look.

**Comment by StevenCostiou** [comment]
Thanks!
It's ok, I can reproduce with less instances, but I needed to know if this is specifically debuggers that are held here.

**Comment by StevenCostiou** [comment]
Fixed by https://github.com/pharo-spec/NewTools/pull/127
