### ISSUE TITLE
When a StDebugger is closed programmatically it is leaked

### ISSUE THREAD

**Issue by tesonep** [pharo-spec/NewTools#125]
When a SPWindow is closed programmatically, the WindowClosed announcement is never generated so it is never removed from the SpApplication window collection.

To reproduce:

- Generate a MNU
- Create the method
- Do proceed.

**Comment by guillep** [comment]
thanksssss

**Comment by tesonep** [comment]
This issue is related to the handling of the close of the window.
The issue window is closed by the execution of the Proceed command, but also the window has a subscription to the change of isClose, that produces to try to clear the debugging session again, producing an error in the subscription, so the window is never removed from the collection of windows. 

I have a solution that is testing if the window has been close by the proceed command it does not execute the clear.
