### ISSUE TITLE
New playground lost search and replace facilities

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/NewTools#132]
We cannot search anymore for string and other. 
Find replace 
and string in methods.

**Comment by Ducasse** [comment]
![Screenshot 2020-11-27 at 11 51 25](https://user-images.githubusercontent.com/432549/100441534-e9ca8480-30a6-11eb-9fc4-2a355fb3927c.png)

**Comment by MarcusDenker** [comment]
this is fixed
