### ISSUE TITLE
StHaltCache should skip the implementation methods on Object

### ISSUE THREAD

**Issue by MarcusDenker** [pharo-spec/NewTools#135]
With my change to unify that everyone uses information based in #isHaltNode, we now get the methods like Object>>#halt listed by the Breakpoint list tool.

What StHaltCache does is that it already filters for 

<haltOrBreakpointForTesting>

we could filter for <debuggerCompleteToSender>, too, which then removes all the implementation methods related to #halt.

Method that needs to be changed:
StHaltCache>>#shouldConsiderMethod:

**Comment by MarcusDenker** [comment]
The "Browse breakpoints" feature we have in the menu is actually not using StHaltCache

I thus did a PR for it in the main repo: https://github.com/pharo-project/pharo/pull/7969

**Comment by StevenCostiou** [comment]
> I thus did a PR for it in the main repo: [pharo-project/pharo#7969](https://github.com/pharo-project/pharo/pull/7969)

I used the same filter as you did.
