### ISSUE TITLE
Proceeding in a debugger leaves zombie morphic render process

### ISSUE THREAD

**Issue by guillep** [pharo-spec/NewTools#136]
In latest Pharo-9.0.0+build.927.sha.71cad16d451fcc2afa17894d6ef5db406e2a25b7 (64 Bit)

To reproduce:
- evaluate `1 halt` to get a debugger
![image](https://user-images.githubusercontent.com/708322/101111019-8eceeb00-35da-11eb-8e52-0e140e82bedd.png)

-  A second UI process will be created. This is **OK**, because the halt happens in a UI process, so a second UI process needs to be created to debug the first one.
![image](https://user-images.githubusercontent.com/708322/101111039-99898000-35da-11eb-8335-a2888906564a.png)

- Click on proceed. The debugged process should finish, but instead it stays there zombie....
![image](https://user-images.githubusercontent.com/708322/101111060-a5754200-35da-11eb-95d5-6ee4572b4e53.png)

**Comment by StevenCostiou** [comment]
Did that appear recently?
I do not remember it, and it has been weeks since I changed stuff in the debugger.

Proceeding calls the following code:
```Smalltalk
proceedDebugSession
	self session
		resume;
		clear
```
It should resume the interrupted process and the hand is given back to the system. Maybe it is more a bug in Oups. I will investigate.

**Comment by guillep** [comment]
That build I tested is from yesterday, if you want to find the culprit you could follow https://thepharo.dev/2020/11/23/bisecting-pharo-versions-to-find-regressions/

**Comment by MarcusDenker** [comment]
keep in mind that a change you did weeks ago showed up in Pharo yesterday. People tell me this is good.

**Comment by StevenCostiou** [comment]
> That build I tested is from yesterday, if you want to find the culprit you could follow https://thepharo.dev/2020/11/23/bisecting-pharo-versions-to-find-regressions/

This is already how I do such investigation, knowing when you noticed it may also help ;)

**Comment by StevenCostiou** [comment]
> keep in mind that a change you did weeks ago showed up in Pharo yesterday. People tell me this is good.

Not sure to understand, you mean *not* good?

**Comment by guillep** [comment]
> > That build I tested is from yesterday, if you want to find the culprit you could follow https://thepharo.dev/2020/11/23/bisecting-pharo-versions-to-find-regressions/
> 
> This is already how I do such investigation, knowing when you noticed it may also help ;)

At the beginning of the issue report I did put the Pharo build info. Do you need something else?

**Comment by StevenCostiou** [comment]
No no, I need nothing more you answered. My original question was if it was the first time it was observed, or if it was only reported now.

**Comment by guillep** [comment]
Ah, ok! Nope, just noticed it yesterday. But I never load newtools manually, I just use what comes with the default image, so maybe the problem is there since a longer time in the newtools repo, or maybe it's just a combination of newtools and something that changed in Pharo in the meantime.

**Comment by pavel-krivanek** [comment]
Can it be a side-effect of the reported memory leak? 
https://github.com/pharo-project/pharo/issues/7953

**Comment by StevenCostiou** [comment]
It is possibly the other way around, because I managed to fix pharo-project/pharo#7953 but that one is still happening, and I see it as a possible reason of pharo-project/pharo#7953.
Maybe it is unrelated.

**Comment by StevenCostiou** [comment]
Found: this is due to this PR https://github.com/pharo-spec/NewTools/pull/127 that, by fixing a leaking of SpApplication, prevents the session to be terminated.
When they terminate, sessions check if they are about a ui process, and if true they terminate it as there should be only one ui process.
Looks like a problem in the sequence of actions done when closing a debugger. Investigating.
