### ISSUE TITLE
NewTools repository management is sick

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-spec/NewTools#137]
My personal attitude is that the repository management of NewTools uses the wrong approach that combines all possible disadvantages. 
Pharo already has projects that are managed as external ones but:
1) they are not so tightly bound to the system
2) they do not have own copy of packages in the repository so no extra synchronization is needed

Please, consider to start using of the Pharo repository as the primary one and use this only to hold extensions and tools that are not in the main Pharo repository. 
Or remove the packages from the Pharo repository and download packages directly from a given version here. I would use the first approach.

**Comment by estebanlm** [comment]
yeah... no :)
