### ISSUE TITLE
Debugger: Add "Fuel out Stack"

### ISSUE THREAD

**Issue by MarcusDenker** [pharo-spec/NewTools#148]
The old debuggers had a nice feature: "Fuel put Stack", that is, write the stack as a re-loadable fuel file.

There is FuelOutStackDebugAction, it needs to be turned into something  like StCopyStackToClipboardCommand

**Comment by StevenCostiou** [comment]
Hm. Now the thing is that it add a dependency from newtools to fuel, that is loaded after newtools.
I have to add another package that contains that dumping behavior and use it as an extension of the stack menu.
This should not be in new tools then but directly in Pharo.

**Comment by StevenCostiou** [comment]
This is a bit complicated to test as the materialization opens a debugger... how do I test that a debugger was opened?

**Comment by StevenCostiou** [comment]
I need to cheat... I will define an exception for opening fueled stack instead of requesting a debugger opening manually

**Comment by StevenCostiou** [comment]
Ok so I did this PR https://github.com/pharo-project/pharo/pull/8141 and hopefully it will be accepted.
