### ISSUE TITLE
remove unused variables

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/NewTools#162]
UnusedVariableRemover new unusedVariables inspect

Should do the same for class variables

**Comment by MarcusDenker** [comment]
The easiest to find them is to run testNoUnusedInstanceVariablesLeft from the browser and look at the "remaining" temp

**Comment by MarcusDenker** [comment]
Class Variables are done

**Comment by MarcusDenker** [comment]
Just two class side instance variables left:

StReporter class
StObjectInspectorPresenter class

I had problems committing a fix, I opened https://github.com/pharo-vcs/iceberg/issues/1479

**Comment by Ducasse** [comment]
Pay attention marcus this is in NewTools and not iceberg.

**Comment by MarcusDenker** [comment]
Yes, but the bug is in Iceberg: I am trying to commit a removal of a class side instance variable, and iceberg can not commit the change (it just ignores it)

**Comment by Ducasse** [comment]
Yes it looks like a bug in iceberg or Monticello. 
May be this is the same as the one I found with the string vs. collection

**Comment by MarcusDenker** [comment]
all done, testNoUnusedInstanceVariablesLeft is now green
