### ISSUE TITLE
Sorting instance variables in an inspector messes up with selection

### ISSUE THREAD

**Issue by guillep** [pharo-spec/NewTools#172]
I inspect an object, I click on one of its fields => a pane in the right is correctly open inspecting the selected object.
If I now sort the elements in the left by name, and click on an element in the list => the selection is wrong
If I sort them again in reverse alphabetic order => selection is also wrong.

With Pablo we think that the selection is using the original order and not the one in the UI

**Comment by MarcusDenker** [comment]
seems to be related to https://github.com/pharo-project/pharo/issues/8490
