### ISSUE TITLE
Inspecting compiled method is wrapping them as RGMethodDefinition and it leads to problems. 

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/NewTools#173]
![Screenshot 2021-02-14 at 14 29 07](https://user-images.githubusercontent.com/432549/107878174-2309d800-6ed1-11eb-9ea4-b13c1547066a.png)

**Comment by Ducasse** [comment]
It looks like the Methods pane in a class inspector is wrapping method into RGMethodDefinitions.
So we do not manipulate compiledMethods.

**Comment by MarcusDenker** [comment]
we removed the "methods" pane in the meantime, so this does not happen
(the meta tab shows the methods)
