### ISSUE TITLE
Do we need StInspectorProtoObjectNode?

### ISSUE THREAD

**Issue by MarcusDenker** [pharo-spec/NewTools#175]
StInspectorProtoObjectNode has no comment.

My theory is that is was added to be able to debug subclasses of protoObject without having to send messages.

But we improved StInspectorSlotNode to do that by default: it reads slots via the slots API and thus we do not need
 StInspectorProtoObjectNode

**Comment by MarcusDenker** [comment]
The problem with StInspectorProtoObjectNode is that is reads via the index, which means it will not work for Slots that are not InstanceVariableSlots.

```
rawValue

	^ thisContext 
		object: self hostObject 
		instVarAt: index

```

While StInspectorSlotNode now does

```
rawValue

	^  slot read: self hostObject

```

Which reads without sending a message to the object, too, but it will work for any kind of slot

**Comment by MarcusDenker** [comment]
What needs to be done:

- change method ProtoObject

```
ProtoObject >> inspectorNodes
 	"Answer a list of attributes as nodes"

 	^ (StNodeCollector for: self) slotNodes
```

- delete class StInspectorProtoObjectNode

**Comment by estebanlm** [comment]
fixed upstream
