### ISSUE TITLE
[Spotter] Cannot return when accepting something while a search is in progress

### ISSUE THREAD

**Issue by guillep** [pharo-spec/NewTools#193]
I had this one a couple of times while trying to reproduce #188

```
Context>>cannotReturn:
Generator>>next
Generator>>yield:
```

![image](https://user-images.githubusercontent.com/708322/112835546-b66e2580-9099-11eb-8e3d-6d9b3a6d7f96.png)

**Comment by estebanlm** [comment]
should be fixed in 0f75a5efcebe19a88ea4154eb7419073fc914420
