### ISSUE TITLE
[Spotter] Spotter does not respond anymore

### ISSUE THREAD

**Issue by guillep** [pharo-spec/NewTools#196]
After playing a bit and having a couple of exceptions, it seems It arrived to some strange state.
I open a new spotter, type something, and not only it does not complete but my machine is "warming up".

I have several open processes that I don't know if they are right or doing the right thing

![image](https://user-images.githubusercontent.com/708322/112835718-f1705900-9099-11eb-9bc9-9e2f02c6ea4a.png)

**Comment by estebanlm** [comment]
this is something with task it: when there is an error inside a scheduled task, weird things happen :(
