### ISSUE TITLE
[Spotter] The set of colors is completely wrong. 

### ISSUE THREAD

**Issue by tesonep** [pharo-spec/NewTools#197]
The light blue arrow is not visible on the gray background.
The toolbar is the most visible thing, and maybe is the less useful.
Selection color on top of the background is not nice.

![image](https://user-images.githubusercontent.com/355455/112836106-70659180-909a-11eb-885d-2a843eb283bd.png)

**Comment by estebanlm** [comment]
yeah, this is not really a spotter problem but a white theme problem (and its icons).
but maybe the remove icon chose can be improved, what do you think on this? 

![image](https://user-images.githubusercontent.com/513630/112951776-07cef100-913c-11eb-8856-94b8384dbf44.png)

(and btw... "completely wrong" is harsh)

**Comment by estebanlm** [comment]
>  The toolbar is the most visible thing, and maybe is the less useful.

which toolbar?

**Comment by tesonep** [comment]
Sorry, I mean the scrollbar. And sorry, if it is harsh, but I cannot see it
without contrast. I am a lot affected when the elements do not contrast.
The same happens with the options. Light blue on top of gray and black
letters, do not help.

The color selection makes my eyes get tired, and it is not confortable.
Maybe it is because I have some limitations to see combinations of colors.

**Comment by estebanlm** [comment]
Ah the scrollbar. Yeah is the most visible thing... I spent some hours trying to make it "stylable" with the purpose of making it less intrusive... buts its colors are **really** hardcoded and it will take some time to do it (and I needed to finish this iteration). 

Still, I agree is a work that needs to be done.

**Comment by estebanlm** [comment]
you see "completely wrong" is not something I can work with. But "I cannot tolerate the contrast" is. 
What about this ? 

![image](https://user-images.githubusercontent.com/513630/112963395-9d23b280-9147-11eb-8dcc-bba02b023646.png)
