### ISSUE TITLE
[Playground] Playground does not have full code search options

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-spec/NewTools#202]
The context menu of playground does not have full code search options as regular code editor has. Options like search for string literals is missing (but shortcut Ctrl + Shift + E works in Playground as well)

![Pharo_xrpUbeKFdk](https://user-images.githubusercontent.com/572494/112839824-e79d2480-909e-11eb-8684-7386100aceae.png)

![Pharo_ZE9pHw13TS](https://user-images.githubusercontent.com/572494/112839837-ebc94200-909e-11eb-854b-5591212f0d65.png)

**Comment by guillep** [comment]
I particularly needed to have case sensitive search to fix this issue:

https://github.com/pharo-project/pharo/issues/9056

The new tools should at least do the same as the old ones, and more...
Maybe if the menu is a bit ugly this could be replaced with an "advanced search" box, dunno

**Comment by MarcusDenker** [comment]
This is fixed, the playground now has the different search options
