### ISSUE TITLE
[Spotter] Results are super strange

### ISSUE THREAD

**Issue by guillep** [pharo-spec/NewTools#203]
- Open spotter
- type `File`

Writing it with different typing speeds, results are different, and they are almost never good (they do not even match!)...

![image](https://user-images.githubusercontent.com/708322/112849358-46679b80-90a9-11eb-8618-85b198c69631.png)

![image](https://user-images.githubusercontent.com/708322/112849549-77e06700-90a9-11eb-9bb4-4200f62db8ff.png)

Typing it slowly yields the right results

![image](https://user-images.githubusercontent.com/708322/112849621-89297380-90a9-11eb-9e3b-ce91028b2b85.png)

**Comment by guillep** [comment]
In some cases, it just returns non-sense, even if typing slowly. Take for example this:

- type `s`
- wait until spinner dissapears
- type `a`
- wait until spinner dissapears
- type `r`
- wait until spinner dissapears
- type `a`
- wait until spinner dissapears
- type `s`
- wait until spinner dissapears
- type `a`
- wait until spinner dissapears

![image](https://user-images.githubusercontent.com/708322/112852499-4a48ed00-90ac-11eb-91b2-2d1fbf07cf72.png)

**Comment by estebanlm** [comment]
fixed 0f75a5efcebe19a88ea4154eb7419073fc914420
