### ISSUE TITLE
[Spotter] introducing modifiers through shortcuts accumulate

### ISSUE THREAD

**Issue by guillep** [pharo-spec/NewTools#205]
- open spotter
- cmd N => it adds "#Senders" (ok!)
- cmd M => it adds "#Implementors" behind "#Senders" (not ok!)
- cmd B => it adds "#Classes" behind (not ok!)
- ...
![image](https://user-images.githubusercontent.com/708322/112858590-4f109f80-90b2-11eb-948d-1fac1d52fea5.png)

**Comment by estebanlm** [comment]
fixing this... old spotter allowed the accumulation of non-equal modifiers (e.g. #Senders #Classes was allowed). But while fixing the accumulation of equal (e.g. #Classes #Classes should not be allowed) I now wonder of that old behavior has sense at all.
