### ISSUE TITLE
[Spotter] New spotter background has problems with the dark theme

### ISSUE THREAD

**Issue by guillep** [pharo-spec/NewTools#209]
The new spotter looks much nicer! Contrast is better, border is nicer. I like the help!

I tried it with the dark theme to see how the contrast worked there, and I found that the background is not themed, but the rest of the spotter yes (selection colors, font colors...)

![image](https://user-images.githubusercontent.com/708322/113297690-38a95480-92fb-11eb-93e9-7f6340a798b7.png)

**Comment by estebanlm** [comment]
no, just changing the dark theme is not automatically changing the pharo application theme.
You need to do `StPharoApplication current resetConfiguration.`
