### ISSUE TITLE
Can we have styling in inspectors header bars?

### ISSUE THREAD

**Issue by StevenCostiou** [pharo-spec/NewTools#23]
I would like to have Text objects in StHeaderBar to put emphasis on the text.
Could that be generalized for all labels?

I can work on that but I want to discuss first.

**Comment by estebanlm** [comment]
you can add styles.
```Smalltalk
myPresenter addStyle: 'myTextStyle'
```

but you need to add the style somewhere :)
this is now defined in SpStyle class>>defaultStyleSheet, in the creator method you will see

```
...
	.label [
		Geometry { #hResizing: true },
		.shortcut [ 
			Draw { #color: Color{ #rgb: 622413393 } },
			Font { #name: "Lucida Grande", #size: 10 }
		],
		.dim [
			Draw { #color : Color{ #rgb: 708480675 } }
		]
	],
...
```

that shows the label has a subclass `dim` that changes the color. 
You can do something like this: 

```
.header1 [ Font { #name: "Lucida Grande", #size: 10 } ]
```
and assign it to your label. 
Now, the only problem here is that I didn't implemented the font weight property (which is what you want to be bold :P). 

And yes, I know all of this require documentation :)

**Comment by estebanlm** [comment]
ok, now is there :)
You can add a style 
```
.label [
    ... 
   .header [ Font { #name: "Lucida Grande", #size: 10, #bold: true } ] 
   ...
]

**Comment by StevenCostiou** [comment]
I cannot make it work.
Besides, if I have a specialized inspector and I need to apply styles only for labels of that inspector, how do I do? 
For instance from the debugger inspector, does that mean I have to dig down to the label and apply a style to it?

**Comment by estebanlm** [comment]
you can have special styles (styles are taken from application, but in the case of Pharo they are the standard styles).
Also, you should not add special styles other than the ones that Pharo will have (this is UI design :P)
Why it does not work?
Did you try resetting the style (its cached).

**Comment by StevenCostiou** [comment]
Well I believe that Pharo style should be header bars with bold title :)
But this is not so simple: when debugging, eg, it makes sense to write things in red sometimes...

So I reseted it and no difference. I tried to put `#bold: true` in the `.shortcut` style which is applied to headers labels in `StHeaderBar` and no effect :'(

**Comment by StevenCostiou** [comment]
Ow, my bad... it was the wrong presenter I was modifying :D
So, it works, thanks! :)

**Comment by estebanlm** [comment]
> Well I believe that Pharo style should be header bars with bold title :)

I could agree with that. But all headers has to be the same ;)
