### ISSUE TITLE
[Playground] does not offer the method source with it

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/NewTools#245]
![Screenshot 2021-06-05 at 14 13 22](https://user-images.githubusercontent.com/432549/120891318-37045180-c608-11eb-8bc3-96b2a2d18470.png)

**Comment by Ducasse** [comment]
To me this is different from 'method literal string with it'.

**Comment by estebanlm** [comment]
yes, it does... the "browse methods containing string" is that (name changed... not my faut ;) ).
what there was not present was precisely the search for strings, which I added Friday (see the PR I just did here: https://github.com/pharo-spec/Spec/pull/1083)

Anyway, when implementing the string search I was mumbling around "why the names of the options are not the same? this is confusing!" and I scheduled a task to unify them (some moment of next week) :)

**Comment by Ducasse** [comment]
Ah cool
Indeed it would be nice to have a unified name and a clear one.

S

**Comment by estebanlm** [comment]
this should be done upstream
