### ISSUE TITLE
[First impressions] There is no feedback when doing a do-it

### ISSUE THREAD

**Issue by guillep** [pharo-spec/NewTools#254]
In the latest versions I find myself doing Cmd+D for do it, and there is no UI feedback to tell me if it happened or not.
Cmd+P effectively prints the result, which is ok. But before the do it used to flicker the text area and select the piece of text that was executed.

In the same sense, the syntax highlighting does not seem to be triggered after a do-it (which is awkward when the do it defines a variable). Typing something forces the syntax highlighting to run, showing that the variable was indeed defined. But without doing that, that causes a bit of confusion.

**Comment by estebanlm** [comment]
this are two different things :)
one is a bug (no syntax highlight)
the other is a feature... afair, there was never feedback of a do it execution. We could add it, but it requires further analysis to not break current flows and that.
For the no highlight, I am opening a new bug.

**Comment by guillep** [comment]
I just checked and in Pharo<=8, after the do it, what was executed gets "selected" with some border (which is not a normal selection).

![image](https://user-images.githubusercontent.com/708322/123384553-d3c96780-d594-11eb-9b86-0e691221211d.png)

**Comment by estebanlm** [comment]
this is just a side effect of the fact that components were not able to execute code that was not selected. 
I can add the behavior (as selection, that "some border" is just some error that looks nice, since the rubric code which was used was just taking the selection or selecting the line before executing :P).

**Comment by guillep** [comment]
Sure, I'm not saying this is urgent nor the best solution, I just find it personally annoying :P

**Comment by estebanlm** [comment]
meh, I restored text selection stuff. 
Which of course, had a bug (if you were at the end of a line "selectLine" was selecting also the separator, which of course was maybe conceptually correct, but it was causing problems, many of theme probably resolvable with "trimRight"... but who knows what else? The print popover, for example, was being popped in a new line, not right after the executed text.
