### ISSUE TITLE
Inspector: we lost the bytecode selection selects the text in the source pane

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/NewTools#261]
In the not so long past, when we inspected a method selecting a bytecode was selecting the expression in the source. 
We lost this super cool functionality.

![Screenshot 2021-07-09 at 14 57 03](https://user-images.githubusercontent.com/432549/125081096-e7f98280-e0c5-11eb-9665-7967a8d766e9.png)

**Comment by estebanlm** [comment]
didn't we fixed that? (long time ago?)

**Comment by MarcusDenker** [comment]
Working again in the last version!
