### ISSUE TITLE
Doing Meta+M in a Class browses GlobalVariable

### ISSUE THREAD

**Issue by tesonep** [pharo-spec/NewTools#266]
- Open a Playground
- Write "Object"
- Put the caret after the "t"
- Meta+M (Ctrl / Cmd)
- It should browse the Object class, but it browses the GlobalVariable class.

The same happens if the shortcut is done selecting the whole word.

**Comment by MarcusDenker** [comment]
A fix: in doBrowseImplementors change

  global browse

to

global value browse

**Comment by MarcusDenker** [comment]
I added a PR to Spec: https://github.com/pharo-spec/Spec/pull/1147

**Comment by MarcusDenker** [comment]
this is now fixed
