### ISSUE TITLE
inspector extra pane should not break when inspecting a strange object

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/NewTools#275]
For example I have a fileReference whose path is a bytestring and the inspector just breaks. 
The inspector should be ROBUST! Else better not have one. 

FileSystem >> absolutePath
	"Return the absolute of the receiver"
	^ self path isRelative
               ~~~~~~~~~~~~
                Raises a DNU because I have a bytestring and not path (ok this is my problem but the inspector should not break). 

		ifFalse: [ self path ]
		ifTrue: [ filesystem resolve: self path ]

S

**Comment by guillep** [comment]
I'm working on this
