### ISSUE TITLE
P9: Duplicate world menu items

### ISSUE THREAD

**Issue by JanBliznicenko** [pharo-spec/NewTools#296]
**Bug description**
Pharo 9 clean image contains duplicate (twice) Playground and Spotter world menu items.

![2021-09-24](https://user-images.githubusercontent.com/9571633/134644601-ffee6f1b-897a-42aa-acc2-7e2efba824fe.png)

**Version information:**
 - OS: Windows (probably irrelevant)
 - Version: Pharo 9 build 1551+
 - NewTools commit: Since 0a30d62 until most recent.
 - Pharo 9 only (issue is not present on Pharo 10)

**Comment by Ducasse** [comment]
Thanks jan I was about to publish it here :)

**Comment by MarcusDenker** [comment]
This was fixed
