### ISSUE TITLE
Inspector Meta tab Browse on class opens UndefinedObject

### ISSUE THREAD

**Issue by JanBliznicenko** [pharo-spec/NewTools#297]
Attempt to "Browse" class in Meta tab of Playground opens browser on UndefinedObject.

![2021-09-26](https://user-images.githubusercontent.com/9571633/134807097-bc841773-1435-4b19-9079-ebb48185daf3.png)

**Steps to reproduce**
1. Open inspector on any object
2. Switch to Meta tab in inspector
3. Right click any **class** in hierarchy
4. Browse

**Expected behavior**
Browser opens on the selected class

**Actual behavior**
Browser opens on UndefinedObject

**Version information**
- Pharo 9 and 10
- All platforms

**Probable cause**
`StInspectorBrowseSelectedCommand` expects 'selectedObject', but it should be 'selectedClass' in case of class right-click ('selectedObject' work only on methods).

**Comment by MarcusDenker** [comment]
StMetaBrowser>>#selectedObject returns the selected method, which is nil in this case.

One possibility is to fall back to the selected class in this case:

selectedObject

	^ self selectedMethod ifNil: [ self selectedClass  ]
