### ISSUE TITLE
Evaluating code in the inspector incorrectly uses binding of on the receiver

### ISSUE THREAD

**Issue by guillep** [pharo-spec/NewTools#312]
Using binding of (see screenshot) is a potential cause of weird errors.
If we are evaluating code in the context of a dictionary, the dictionary is used for variable lookup, even though its keys may not be names, or we are not intending to.

![image](https://user-images.githubusercontent.com/708322/140726166-9366d050-ce00-4a9c-94c8-49263ff43f20.png)

See for example the case below:

![image](https://user-images.githubusercontent.com/708322/140726542-82d0431f-e004-46cf-a75d-eba133d7014c.png)

If I'm on a dictionary, variables are looked up in the dictionary, producing a DNU instead of a more decent compiler error because the name is not defined.

**Comment by MarcusDenker** [comment]
I am analyzing it... on the level of the UI #bindingOf: I think just has to do anything *if* the UI adds bindings (like the Playground, and the debugger which looks up via the context, too).

#bindingOf: in Object is defined to return nil, anyway. So we just do something else it is overridden, which is exactly the case we see here, leading to an error.

So for now, the solution is to implement #bindingOf: and #hasBindingOf: to return nil and false for SpCodeObjectationModel.

(the others need to be checked, too, and the whole mechanism re-thought. To me it looks like this should be all simpler. It could be that most of the complexity comes from Newtools of course using what is there on the compiler level, which needs to be improved there).
