### ISSUE TITLE
Button to browse selected method in debugger is missing

### ISSUE THREAD

**Issue by carolahp** [pharo-spec/NewTools#323]
The old debugger has a button to browse the method selected in the call stack. 
The new debugger provides this functionality in a contextual menu but it is harder to find. 

I would like to add a new button with this functionality as in the old debugger

**Comment by StevenCostiou** [comment]
Hi Caro, now you can double click on the method to open it (see https://github.com/pharo-spec/NewTools/pull/460).
I hope it works for you, if not please reopen the issue.
