### ISSUE TITLE
Raw inspector on Array: breakpoint menus should be disabled

### ISSUE THREAD

**Issue by MarcusDenker** [pharo-spec/NewTools#349]
When inspecting an Array, we should disable the menus that make only sense for slots:
![Inspector-breakpoint-Disable](https://user-images.githubusercontent.com/413057/155339596-71195867-f7d1-475a-9a10-24009f75aa9d.jpg)

What needs to be done: add StBreakpointCommand>>#canBeExecuted

```
canBeExecuted
	^	context selectedItem class == StInspectorSlotNode
```

**Comment by StevenCostiou** [comment]
This has a side-effect on the meta-side tab of the inspector.
See https://github.com/pharo-project/pharo/issues/11213
At least in class `StHaltOnCallCommand` class, the method `canBeExecuted` should call `self appliesTo:` instead of the code from this PR, or just returning `true`.
