### ISSUE TITLE
"Do it" icon label in playground not properly displayed

### ISSUE THREAD

**Issue by demarey** [pharo-spec/NewTools#355]
![Capture d’écran 2022-03-16 à 10 48 16](https://user-images.githubusercontent.com/2494203/158565100-a7a79ebc-a0e7-4234-8a73-737b713fa686.png)

**Comment by pavel-krivanek** [comment]
Does it preserve even after the image saving? It looks like the font issue we still have sometimes.

**Comment by demarey** [comment]
You're right it is related to the font problem.
The problem is gone after saving.
I close the issue. 
To keep some trace, what is the issue number for the font pb?
