### ISSUE TITLE
[Debugger] Debugger allows to create methods in superclass of method defining subclassResponsibility

### ISSUE THREAD

**Issue by hogoww** [pharo-spec/NewTools#356]
@StevenCostiou Could have the debugger label please ? =]

**Bug description**
Bug 1 When using the debugger to create an override for a subclassResponsibility method, we can install the method in a superclass of the class defining the subclassResponsibility method.
-> The context changes to execute this newly created method in the debugger (which is okay)
-> Upon reexecuting the code, you encounter the subclassResponsibility method a second time, and the """override""" is (of course) never called.
=> Solution would be to only scope to the class defining the subclassResponsibility method and its subclasses.

Bug 2 (ish)
There is no indentation in front of the classes names.
There is in calypso a presenter that is already handling this.
You can see https://github.com/pharo-project/pharo/issues/11052 for a bit of details about it.

**To Reproduce**
1. Create a new class
2. define a subclassResponsibility method
3. Execute the method with the subclassResponsibility
4. The debugger stops
5. Click on Create method
6. The command StDefineSubclassResponsabilityCommand is invoked
7. It proposes to instal the method in every classes up until protoObject

**Expected behavior**
Bug 1 The debugger should not allow to define a method that cannot be called using the same code.
Bug 2 displaying hierarchy with tabs.

**Screenshots**
Bug 1
![Screenshot 2022-03-25 at 12 13 12](https://user-images.githubusercontent.com/21278554/160110806-72e8219d-12a3-4651-b048-9fdbeb7d8d87.png)

Example of hierarchy displayed by Calypso
ClyMethodEditorToolMorph >> #chooseClassForNewMethodIfNone: 
![Screenshot 2022-03-25 at 12 14 38](https://user-images.githubusercontent.com/21278554/160111007-41ccaad2-af57-49ec-9ba5-d84eb34d30de.png)

**Version information:**
Pharo 10.

**Expected development cost**
1) fairly easy.
2) fairly easy.
This is of course unless we were to unify Calypso & the Debugger for this particular presenter

**Comment by adri09070** [comment]
I'll try to do this with @RomainDeg during today's sprint
