### ISSUE TITLE
The debugger action model is not updated automatically, needs refactoring

### ISSUE THREAD

**Issue by adri09070** [pharo-spec/NewTools#367]
When an instance of `StDebugger` is notified with an event, the debugger action model is not updated automatically. This is the case, when it is notified that the session's state has changed, or when a new method has been created. For instance:
 
```Smalltalk
updateStep
	self flag: #DBG_UPDATE_OF_MODEL_SHOULD_BE_AUTOMATED.
	debuggerActionModel updateTopContext.
	debuggerActionModel updateContextPredicate.	
	debuggerActionModel updateDebugSession.
		
	self updateStackFromSession: self session.
	self updateWindowTitle.
	self updateExtensionsFrom: self session.	
	self updateToolbar.
	self flag: #DBG_INSPECTOR_UPDATE_BUG.
	inspector getRawInspectorPresenterOrNil ifNotNil: [ :p | p update ]
```

This is a problem because the debugger action model is part of the debugger's logic, so it should be able to exist without a GUI.

Furthermore, the session is encapsulated in a session holder, through which the debugger accesses the session. However, it is not needed as the debugger action model can now access the session, so it could notify the GUI when the session has changed. As a result, all session events and system announcement events should be moved to the action model so that it can update automatically.

To finish with, each session event triggers the call of a specific method but all these methods call the same method: `updateStep`. For instance:

```Smalltalk
updateStepInto
	self updateStep
```

Methods like these are unused hooks so they can be removed in the process of the refactoring

**Comment by adri09070** [comment]
Is it possible to reopen this issue and the associated PR or do I have to create new ones ? @MarcusDenker

**Comment by MarcusDenker** [comment]
Issue is easy to re-open, for the PR I think one needs to redo it (as it was merged and then un-done)

**Comment by adri09070** [comment]
I'm confused because now, I can't do another PR because GitHub says that my branch is not ahead of Pharo-spec:Pharo11... But you reverted the changes so, it should be ahead

What can I do to do a new PR with the same commits as the other one ?

**Comment by adri09070** [comment]
I discovered that we can checkout branch and revert the revert and create a new PR with that...

But there will only be one commit instead of all commits I initially had

**Comment by MarcusDenker** [comment]
ah, good. I guess losing the intermediate commits is not that of a problem (I think there is  even a style arguing that every PR should be one commit and intermediates should be merged)

**Comment by adri09070** [comment]
Ok, I'll do it then
