### ISSUE TITLE
[Inspector] Browse action from the context menu in the Meta tab does not work

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-spec/NewTools#412]
In the inspector, "Browse" action from the context menu in the Meta tab does not work. It browses the UndefinedObject.

## How to reproduce

1) Open inspector on an Integer like 42, go to the Meta tab, open context menu on a class and do "Browse"

![image](https://user-images.githubusercontent.com/572494/187708613-f8a54d0e-1739-4254-b267-6cde0d8a43a6.png)

2) The browser on `UndefinedObject` is always opened

**Comment by pavel-krivanek** [comment]
The problem is that for the `StMetaBrowser`, only the selected method is taken into account, see `StMetaBrowser>>#selectedObject`

**Comment by pavel-krivanek** [comment]
I propose to fix it like this:
```smalltalk
selectedObject

	^ self selectedMethod ifNil: [ self selectedClass ]
```
- so if no method is selected, the class is browsed (and if a method is selected, the method inside the class is browsed witch is acceptable)

**Comment by MarcusDenker** [comment]
I did a PR that fixes is like that: https://github.com/pharo-spec/NewTools/pull/416
