### ISSUE TITLE
`#isReturnSpecial was sent to nil` while debugging in playground

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/NewTools#456]
I got this error while debugging in the playground. 

To reproduce: 
- Open a playground
- Type `1 + 1`
- Select all
- Do ctrl + shift + d

![image](https://user-images.githubusercontent.com/9519971/216563680-1cb7bdc9-ce6c-45b4-996a-cd10992f8a72.png)

**Comment by adri09070** [comment]
I am not able to reproduce it with the steps above in the latest version of Pharo.

This is weird

**Comment by jecisc** [comment]
I just tried in a new image and I don't get this error anymore. 

I'll close it and reopen later if I can reproduce
