### ISSUE TITLE
Debugger: Instance of SindarinDebugger did not understand #moveToNode:

### ISSUE THREAD

**Issue by labordep** [pharo-spec/NewTools#474]
Missing method found in : 

`SindarinJumpToCaretCommand>>execute`

![image](https://user-images.githubusercontent.com/49183340/222920045-49b42bb2-cfca-4508-ac5a-2d4ecc03d8eb.png)

**Comment by adri09070** [comment]
Yes, I just found out that the version of Sindarin that is loaded is not the right one

**Comment by adri09070** [comment]
I think it can be closed via https://github.com/pharo-spec/ScriptableDebugger/pull/59, but we can wait for another build to be sure that it has been really fixed

**Comment by adri09070** [comment]
Now, it works.

Closed via https://github.com/pharo-spec/ScriptableDebugger/pull/59
