### ISSUE TITLE
Debugger: Adding an instance variable not appears in the debugger vars inspector + args duplication when restarting execution

### ISSUE THREAD

**Issue by labordep** [pharo-spec/NewTools#475]
I have detected a problem when I'm coding in the debugger. 

See my video to follow explaination : 
https://user-images.githubusercontent.com/49183340/222958834-73167518-8ba8-4223-b611-f5960741e91c.mp4

The case is : 
- Debug an object method with an entry arg
- Add an instance var (to simulate a development)

Problems was : 
- The new var is not display in debuggervar inspector list (at the bottom)
`thisIsVar` is not here :
![image](https://user-images.githubusercontent.com/49183340/222959078-2a378d63-e3ba-4183-95b1-e30e497014d5.png)

- At each "restart" of the execution, the method entry arg is duplicated in the var inspector list (at the bottom) - this is probably another problem because this arriving without code modification
![image](https://user-images.githubusercontent.com/49183340/222959033-efc5656d-884b-44ef-960e-37e56e398a53.png)

The code if you want to reproduce, this is simple to rewrite :
[MyClass.zip](https://github.com/pharo-spec/NewTools/files/10891733/MyClass.zip)

The playground : 
```
myClass := MyClass new.
myClass setMethod: 'Hello I am an argument'.
```

My config : 
- Pharo-11.0.0+build.593 64 bits
- Windows 11 Pro

**Comment by adri09070** [comment]
I haven't managed to load your video.

But I'll check it out

**Comment by labordep** [comment]
Hi @adri09070, I can send a gif if you prefer but it's bad to have a time control :-(

**Comment by adri09070** [comment]
I think it's ok. I manage to reproduce what you described
