### ISSUE TITLE
Halt on Call in Meta browser in the inspector is disabled

### ISSUE THREAD

**Issue by adri09070** [pharo-spec/NewTools#480]
![image](https://user-images.githubusercontent.com/97704417/223995768-4850651c-6621-4fe3-9361-052adc4c83d7.png)

**Comment by adri09070** [comment]
This is because: 
```Smalltalk
StHaltOnCall>>#canBeExecuted
  ^ context enableSlotMenuEntries
```

Here `context` is an instance of `StMetaBrowser`, which executes the method from `StInspection` :

```Smalltalk
StInspection>>#enableSlotMenuEntries
	^false
``` 

Any idea of why we need this and why it doesn't work @StevenCostiou ? I don't event know what a slot menu entry is.

It works for the 3 other object-centric breakpoint commands because they use the `StRawInspection`

**Comment by StevenCostiou** [comment]
Changed here https://github.com/pharo-spec/NewTools/commit/04981939090598627d45d0f9e9e95bdc9e1973ca by @MarcusDenker 
It seems it wrongly disables the halt on call menu entry in the meta-pane.

**Comment by adri09070** [comment]
Yes, I just saw that

**Comment by adri09070** [comment]
https://github.com/pharo-spec/NewTools/pull/387

This PR was to fix a bug in the meta inspector but ever since, it has been disabled

**Comment by StevenCostiou** [comment]
I do not understand the original problem :/

**Comment by adri09070** [comment]
The problem was : https://github.com/pharo-project/pharo/issues/11213 . `StMetaBrowser` didn't understand the message `#selectedItem` which broke the contextual menu as `StHaltOnCall` sent this message to the meta browser in its `#canBeExecutedMethod`.

This bug appeared with this PR : https://github.com/pharo-spec/NewTools/issues/349
And it seems you had already highlightened the problem

**Comment by StevenCostiou** [comment]
Hmm so should we  just do:
```Smalltalk
StMetaBrowser>>enableSlotMenuEntries
	^true
```
?

**Comment by adri09070** [comment]
I tried to do: 

```Smalltalk
StHaltOnCall>>#canBeExecuted
	^ self appliesTo: context
```

and it looks like it produces the expected behavior.

Do I do a PR right away or do I wait until Marcus checks the original issue ?

**Comment by StevenCostiou** [comment]
Please do a PR ;)

**Comment by MarcusDenker** [comment]
Yes, looks good. The fix I did was not good
