### ISSUE TITLE
Debugger: Exception "Breakpoint not found in OrderedCollection" when creating a new method from the debugger

### ISSUE THREAD

**Issue by labordep** [pharo-spec/NewTools#485]
I found a bug that appears when developing in the debugger. I have writen a reproductible process. 
**Watch my video to have the detailled and complete illustration of the case.** 

1. **Create a new unit test** using an existing with changing this method name. **Debug** the test. The test is opening in a debugger.

![image](https://user-images.githubusercontent.com/49183340/225456039-0a4d1425-7566-468e-97e9-71b8ee602aa8.png)

2. Add a non existing method in the source code of the test, in my example this is `numberOfSystems` and accept the new source code. The new non existing method is red.

![image](https://user-images.githubusercontent.com/49183340/225455809-f14a5d21-5fee-4045-ae6a-03e1af3762d7.png)

3. Always in the debugger window, do `proceed` ![image](https://user-images.githubusercontent.com/49183340/225456662-bb8749fb-6d72-414d-b675-1b870fb73679.png), **a new debug window is opening** due to the non existing method.

![image](https://user-images.githubusercontent.com/49183340/225456906-226fc261-0116-4153-b51e-3bb8f0ed3dcf.png)

4. **Create** the method with the button in the debugger button bar  
![image](https://user-images.githubusercontent.com/49183340/225457005-53b97d88-936d-4b16-9ad4-e530b2b2c57a.png)
 and select a `Class` and a `protocol`.

5. **Implement** the new method and **Accept** the source code.

![image](https://user-images.githubusercontent.com/49183340/225457204-740a16c3-dec1-48bb-b5fc-42a4db71ac06.png)

**At this step all is normal.**

6. Do a Proceed from the debugger window (used to implement the new method)

![image](https://user-images.githubusercontent.com/49183340/225457405-67fba289-b6e7-4ca1-8ad6-9297edbdf6c1.png)

7. An exception appears !

![image](https://user-images.githubusercontent.com/49183340/225457617-2c481b69-d0e9-4c6c-a90d-d09899423656.png)
 
The complete video illustration :

https://user-images.githubusercontent.com/49183340/225457675-d755e4a2-b2f4-4c2b-82c5-cf75ac12ecd5.mp4

**Comment by labordep** [comment]
My configuration :
- Windows 10 Profesionnal
- Pharo-11.0.0+build.623 (64 bits)

**Comment by adri09070** [comment]
It's rather a problem of Calypso because when you run a test from Calypso, it will put a breakpoint on the AST method node of the test in order to stop at the beginning of the method to debug. 

Then it uses `ensure:` to remove  the breakpoint when the test is finished.

Then, by changing the method under debug and by recompiling the method, it also changes the AST. Notably, the metalink doesn't exist anymore. So it is wrong from Calypso to systematically remove the breakpoint. It should remove it only if the breakpoint still exists.

I'll open an issue on the Pharo repository

**Comment by labordep** [comment]
Thanks @adri09070 for your explainations.

**Comment by adri09070** [comment]
Closed via https://github.com/pharo-project/pharo/pull/13021
