### ISSUE TITLE
Inspector needs more extensions

### ISSUE THREAD

**Issue by svenvc** [pharo-spec/NewTools#496]
Way back I contributed many inspector extensions to Pharo. With the move to Spec and NewTools many of those are gone. Now that the dust seems to have settled, I would like to contribute again, porting as much of the old ones as I can.

It was always my idea to have a functional abstraction for simple cases. I created a little helper class (included at the end as a file out). The idea is that Spec specialists can improve the UI code for everyone. I am already happy, but I want some feedback and I am missing one feature that I think is important.

More comments after the PR.

**Comment by svenvc** [comment]
PR: https://github.com/pharo-spec/NewTools/pull/497

**Comment by svenvc** [comment]
My main problem is that I (sometimes) want to make a difference between what is shown in the values column and what is used to dig deeper when you click on some aspect.

Right now, by cheating a bit, it works here and there, but it is not good enough.

For example, the character aspect of an Integer now has the actual Character instance as value, but it renders as A and not $A which would be better. The codepoint aspect of a Character works because it is a simple Integer where no special rendering is needed.

Another example are the UTF8 en Latin1 encodings of a String: I want one representation in the column, but the actual ByteArray instance as drill down value.

I know that for other examples I need this difference as well. I thought I could use StInspectorAssociationNode as items, but that did not work out fully. And it felt like a misuse.

It would also be nice to make the keys column smaller.

What would be the best ways to handle large collections ?

What do you think ?

**Comment by jecisc** [comment]
For large collections maybe we could have something like in string? The default tab with a subset of the collection and a "full" tab that might take longer for people knowing what they are doing?

For the drill down, I agree that we might have a different value than the row clicked. I don't know enough the new inspector to know the best way to do that tho

Thank you a lot for this. The inspector extensions are really really useful!

**Comment by svenvc** [comment]
Yes, inspector extensions are important and powerful. Especially when they are combined. That is why this chaining, and possible showing something else that what you inspect if you click to drill down, is so important.

Like @MarcusDenker says: each addition is a small step, but it is a self-improving, growing system, a positive feedback loop.

**Comment by svenvc** [comment]
Yes, inspector extensions are important and powerful. Especially when they are combined. That is why this chaining, and possible showing something else that what you inspect if you click to drill down, is so important.

Like @MarcusDenker says: each addition is a small step, but it is a self-improving, growing system, a positive feedback loop.

**Comment by svenvc** [comment]
Yes, inspector extensions are important and powerful. Especially when they are combined. That is why this chaining, and possible showing something else that what you inspect if you click to drill down, is so important.

Like @MarcusDenker says: each addition is a small step, but it is a self-improving, growing system, a positive feedback loop.

**Comment by svenvc** [comment]
Any feedback @estebanlm ?

Any chance this could be integrated ?

**Comment by svenvc** [comment]
Gracias!
