### ISSUE TITLE
Inspector needs more chronology extensions

### ISSUE THREAD

**Issue by svenvc** [pharo-spec/NewTools#498]
We need inspector extensions for Date, Time, DateAndTime and Duration.

**Comment by svenvc** [comment]
Waiting: https://github.com/pharo-spec/NewTools/commit/e7d83a4e0490df4c66cb54f498013bdc1633504d

**Comment by svenvc** [comment]
PR: https://github.com/pharo-spec/NewTools/pull/499

**Comment by svenvc** [comment]
![Screenshot 2023-03-28 at 14 46 10](https://user-images.githubusercontent.com/870089/228240690-9034746d-df3e-453f-bcff-d4a7a473aef0.png)

**Comment by MarcusDenker** [comment]
merged
