### ISSUE TITLE
Inspector: `self` is nil in Meta tab

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/NewTools#507]
In the Meta tab of the inspector, if you inspect self you get nil instead of your inspected object. 

It seems the evaluator presenter is not the same than in the other tabs and that makes it impossible to script in the Meta tab.

**Comment by hernanmd** [comment]
It seems the intended use of the presenter below the Meta hierarchy is not to be an evaluator but a selected method viewer.
So this situation only arise after the initial click in the Meta tab. 

The issue then would me more a usability one, to go back and forth to an evaluator in the Raw tab and Meta tab.

What do you think about selecting a method by default after the Meta tab is clicked?
