### ISSUE TITLE
[Debug] Jump to carret problem - Instance of InstructionStream did not understand #willJumpIfFalse

### ISSUE THREAD

**Issue by labordep** [pharo-spec/NewTools#538]
During a debug, I want to move the cursor using "Jump to caret" 
![image](https://github.com/pharo-spec/NewTools/assets/49183340/6a64d5dc-8881-42b5-b101-955b1765ed2d)

But I have an error : 
![image](https://github.com/pharo-spec/NewTools/assets/49183340/ffc83288-b100-409b-962f-f12b3da380e3)

I'm debuging this method :
![image](https://github.com/pharo-spec/NewTools/assets/49183340/58a8cc2f-34de-4841-aa8f-1c402cd05d6f)

And I want to jump here : 
![image](https://github.com/pharo-spec/NewTools/assets/49183340/b29b1420-b684-4c0f-8290-a55749e0345c)

**Comment by labordep** [comment]
Same problem with 
![image](https://github.com/pharo-spec/NewTools/assets/49183340/83e91b0f-6e59-4fce-a552-65c1f217077d)

**Comment by labordep** [comment]
My config : 
- Windows 10 Pro
- P11 release 64 bits

**Comment by Ducasse** [comment]
Thanks pierre! Tests are missing.

**Comment by StevenCostiou** [comment]
@jecisc @adri09070 This is the method that you removed from Sindarin?

**Comment by jecisc** [comment]
We removed it in the Pharo 12 branch. I don't think the Pharo-11 branch got touched

**Comment by StevenCostiou** [comment]
this is odd I just tested on a fresh image and it works.
The method is there in Sindarin.

![Capture d’écran 2023-05-31 à 15 27 36](https://github.com/pharo-spec/NewTools/assets/26929529/3184766a-01db-4d7a-aaec-e48a3a7f3f67)

@labordep Did you reload Sindarin, or another project?

**Comment by StevenCostiou** [comment]
Does it mean the method was later added to Pharo and not deleted from Sindarin?

**Comment by jecisc** [comment]
IIRC: This method was present as an extension provided by Debugger-Model and also as an extension provided by Sindarin. This made Sindaring remove some code that was present in Pharo. 

I removed in Pharo12 branch the method of Sindarin so that Sindarin use the version from Pharo of this method.

**Comment by StevenCostiou** [comment]
It was Debugging-Core, and it is present in P12 and P11, and last time this code was touched is 5 years ago so it was there.

See https://github.com/pharo-project/pharo/blame/Pharo11/src/Debugging-Core/InstructionStream.extension.st

But there in Pharo12 and 11 when I create a new image, it is already there.
An hypothesis could be that @labordep you load something that messes it up.
Did you load any of our debugging projects maybe that could have a dependency?

**Comment by adri09070** [comment]
@labordep I would say this is normal it doesn't work if you loaded Sindarin and if you use the master branch Sindarin on Pharo-11.

Is it the case?

If this is the case, you should use the Pharo-11 branch of Sindarin

**Comment by adri09070** [comment]
Still, it's weird that it doesn't work because the method exists in Debugging-Core. I wonder if the problem happens in Pharo12.

But at least, you are sure that  the method exists on the Pharo-11 branch

**Comment by labordep** [comment]
@adri09070 @StevenCostiou, Yes I have Sindarin.

To be complete I have that : 

```smalltalk
"Chest"
Metacello new
    baseline: 'Chest';
    repository: 'github://pharo-spec/Chest';
    load.

"Sindarin"
Metacello new
    baseline: 'Sindarin';
    repository: 'github://pharo-spec/ScriptableDebugger';
    load.

"AST"
Metacello new
    baseline: 'DebuggableASTInterpreter';
    repository: 'github://adri09070/DebuggableASTInterpreter';
    load.

"Seeker"
Metacello new
    baseline: 'Seeker';
    repository: 'github://maxwills/SeekerDebugger:main';
    load.
```

**Comment by adri09070** [comment]
On Pharo 11, you should use 

```Smalltalk
"Sindarin"
Metacello new
    baseline: 'Sindarin';
    repository: 'github://pharo-spec/ScriptableDebugger:Pharo-11';
    load.
```
instead of

```Smalltalk
"Sindarin"
Metacello new
    baseline: 'Sindarin';
    repository: 'github://pharo-spec/ScriptableDebugger';
    load.
```

Still, it doesn't "feel normal" that you cannot use the master branch on Pharo-11, I will try to find a solution

**Comment by labordep** [comment]
Thanks @adri09070, I will test. But normally the baselineOf should select the correct branch for my image version ?

**Comment by adri09070** [comment]
I just tried, and when I select the branch Pharo-11, I have... nothing...

![image](https://github.com/pharo-spec/NewTools/assets/97704417/6a38ef1f-a519-4899-908b-e3f843bc5c6f)

Thanks Iceberg...

**Comment by adri09070** [comment]
But all looks good with a Metacello script...

Anyway, I think I found a solution to be able to use the master branch in Pharo11
