### ISSUE TITLE
Exception : Instance of DebuggerSelector did not understand #closeAllDebuggers

### ISSUE THREAD

**Issue by labordep** [pharo-spec/NewTools#54]
(Not sure if the problem is concerned by the new debugger)
When trying to "close all debuggers" (from "Windows" button on the main menu).

**Comment by StevenCostiou** [comment]
@dupriezt see commit 744b107cde221376bf21e1e41f89fc393693b226 I fixed it with a hack for Pierre but it needs more love :)
