### ISSUE TITLE
Debugger: show thisProcess lile thisContext as implicit var

### ISSUE THREAD

**Issue by MarcusDenker** [pharo-spec/NewTools#543]
The Debugger always shows thisContext:

![debugger](https://github.com/pharo-spec/NewTools/assets/413057/0db4a8ea-a7ca-4f29-82d7-40e81e30284b)

We now could add thisProcess as a implicit var, too.

**Comment by adri09070** [comment]
Adding `thisProcess` to the inspector is very easy.

What I wonder is: do we need to do more than just adding it to the inspector?

I tried to inspect `thisProcess` in a debugger and it keeps changing constantly (I don't know if this is normal):

![image](https://github.com/pharo-spec/NewTools/assets/97704417/b1f12929-6432-48de-8448-96ea0ef38de7)

![image](https://github.com/pharo-spec/NewTools/assets/97704417/a462e4ab-a16d-42e9-b687-54e9a2523610)

**Comment by MarcusDenker** [comment]
Yes, inspecting thisProcess is not working correctly right now, the reason is that it just uses "Processor activeProcess", but without settign the effectiveProcess (and effectiveProcess is a bad hack, too).

I did a fist wrong PR (https://github.com/pharo-project/pharo/pull/13877), I will close that and open an issue with all the ideas we had (e.g. there is the idea to add the process to the DoItVariable)

**Comment by MarcusDenker** [comment]
I think having thisProcess in the inspector is not really needed for now
