### ISSUE TITLE
Skipping execution is broken when we step in bytecode and try to skip at the wrong position

### ISSUE THREAD

**Issue by StevenCostiou** [pharo-spec/NewTools#55]
- use double dispatch on nodes to know what skipping strategy to use instead of switch case
- take into account nodes on which a bytecode step has been done (*e.g.* variable nodes receiver of messages)

That may not be simple, as depending on the parent (*e.g.*, assignment or message or...?) what we have to pop from the context and how much we should advance the pc is not obvious.

**Comment by adri09070** [comment]
If I understand well, it has been fixed on Sindarin's side
