### ISSUE TITLE
Debugger: var duplication (and big slowdown) when executing a loop with "run to" action

### ISSUE THREAD

**Issue by labordep** [pharo-spec/NewTools#607]
When I'm debugging a loop I have a lot of `temp var` and `arg` duplicated in the debugger inspector.
In the video below you can note the time to execute the `run to` action (very long).

The loop: 

![image](https://github.com/pharo-spec/NewTools/assets/49183340/b15d86e5-7888-4ffd-bbc4-4eedbe952df2)

The problem: 

![image](https://github.com/pharo-spec/NewTools/assets/49183340/efd32bfd-bdfe-4d19-94e4-cbf282c061a5)

A video catured during execution:

https://github.com/pharo-spec/NewTools/assets/49183340/affffaa0-15f2-4cca-98da-7c45ff3bb584

This issue is similar to https://github.com/pharo-spec/NewTools/issues/475 previous one.

My config: 
- Windows 11 Pro
- Pharo-11.0.0+build.707
- VM 10.0.8.0

**Comment by labordep** [comment]
Thanks @StevenCostiou and @adri09070, is it fixed in P11 ?

**Comment by StevenCostiou** [comment]
no but maybe we can backport, i do not know how to do i @adri09070 @estebanlm

**Comment by adri09070** [comment]
I think it needs another fix because the fix relies on the new debugger event system in P12.

I could fix the bug in P11, but differently
