### ISSUE TITLE
expression finder didn't find expression

### ISSUE THREAD

**Issue by vonbecmann** [pharo-spec/NewTools#614]
Pharo image: Pharo12.0.0#121090
Virtual machine used: CoInterpreter VMMaker-tonel.1 uuid: 2ec2f2fc-b3c1-0d00-af03-1dc00bccb44d Sep 14 2023
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: 2ec2f2fc-b3c1-0d00-af03-1dc00bccb44d Sep 14 2023
v10.0.7 - Commit: b66dd58 - Date: 2023-09-13 15:14:31 +0200

Platform Name: unix
Class browser used (if applicable): ClyFullBrowserMorph

Steps to reproduce:
#. Library>>Expression Finder
#. search for:
```
`@receiver copyFrom: 2 to: `@receiver size
```
#. Find in selected classes
#. Packages: System-Hashing
#. Classes: select all
#. click Ok

Actual Result:
#. 0 matches found

Expected Result:
#. DigitalSignatureAlgorithm class>>#initialize
```
initialize
	"DigitalSignatureAlgorithm initialize"

	"SmallPrimes is a list of small primes greater than two."
	SmallPrimes := Integer primesUpTo: 2000.
	SmallPrimes := SmallPrimes copyFrom: 2 to: SmallPrimes size.

	"HighBitOfByte maps a byte to the index of its top non-zero bit."
	HighBitOfByte := (0 to: 255) collect: [:byte | byte highBit]
```

**Comment by Ducasse** [comment]
This is strange. It looks like the pattern matcher does not handle such variables.
It would be great if you had some time to investigate this point more because we are currently flooded but the 
matcher is an important tool.

**Comment by Ducasse** [comment]
Would be interesting to see the expression with RBParseTreeMatcher to remove the finder.
