### ISSUE TITLE
"Do it" button of the StPlayground does not work

### ISSUE THREAD

**Issue by badetitou** [pharo-spec/NewTools#62]
When executing the Do It button *with at least some code inside the playground* a debugger appears.
I suppose it is a problem with the context given to the command or a missing method in StPlayground 

`MessageNotUnderstood: StPlayground>> #doItReceiver in SpCodeInspectItCommand(SpCodeSelectionCommand)>>evaluate:andDo:`

![bug playground](https://user-images.githubusercontent.com/6225039/82884206-b8c89600-9f43-11ea-9248-f9d1870cdc58.gif)

(however it does work if I execute using Ctrl+D )

**Comment by estebanlm** [comment]
fixed upstream
