### ISSUE TITLE
[Debugger][P12] Recompiling code within a bloc cannot be done more than once in the debugger

### ISSUE THREAD

**Issue by adri09070** [pharo-spec/NewTools#722]
If you have a bloc closure like this, called via a method

```Smalltalk
MyClass>>mySortBlock

	^ [ :a :b | a < b ]
```

Then, you can paste this code in a playground and debug it (with one `stepOver` and one `stepInto`:

```Smalltalk
anObject := MyClass new.
anObject mySortBlock value: 1 value: 2
```

In the debugger, try to modify the code of the bloc, for example by adding a halt:

```Smalltalk
MyClass>>mySortBlock

      ^ [ :a :b | self halt.  a < b ]
```

 and save the changes.

A popup will open, click on "Compile and browse".

A browser will then open on the embedding method with the new code:

![image](https://github.com/pharo-spec/NewTools/assets/97704417/175f51b2-d5d2-4070-a5f4-0f9acfdc91e2)

Close this browser.

Then, in the debugger, change the code in the bloc again, for example by commenting the halt you've just added:

```Smalltalk
MyClass>>mySortBlock

      ^ [ :a :b | "self halt."  a < b ]
```

Save the changes, confirm the popup by clicking "compile and browse".

A browser opens on the method that hasn't been modified: the halt isn't commented:

![image](https://github.com/pharo-spec/NewTools/assets/97704417/9b68abfc-e5c6-4aa4-a555-1aec6b6a1fdc)

**Expected behavior:**

The method should have been recompiled with the new code (i.e: with the commented halt)

**Comment by Ducasse** [comment]
Oh yes I got bitten by this bug.

**Comment by adri09070** [comment]
Well, I've done the fix some months ago and it's still not integrated. 

https://github.com/pharo-project/pharo/pull/16319 should be merged and then https://github.com/pharo-spec/NewTools/pull/723

@StevenCostiou

**Comment by Ducasse** [comment]
@adri09070 I do not understand because the issue is integrated.

**Comment by Ducasse** [comment]
I understand that you are not happy but if people do not review PRs then they do not get reviewed. 
And now this is difficult to follow what is happening because of the dependencies between projects. 
Now I do not get why the test is failing even if I merged https://github.com/pharo-project/pharo/pull/16319

**Comment by adri09070** [comment]
Now, the test is green

**Comment by adri09070** [comment]
Now, for the backport, do I need to create these PRs again targeting the Pharo12 branch or are you able to merge the same PR into the Pharo12 branch?
