### ISSUE TITLE
Creating a method in a debugger fails to ask the protocol

### ISSUE THREAD

**Issue by tesonep** [pharo-spec/NewTools#76]
To reproduce debug a MessageNotUnderstood and click on create:

Instance of AbstractTool class did not understand #requestProtocolNameFor:initialAnswer:
AbstractTool class(Object)>>doesNotUnderstand: #requestProtocolNameFor:initialAnswer:
StDebugger>>requestCategoryIn:
StDebugger>>createMissingMethodFor:in:
StDebugger>>createMissingMethod
StDefineMethodCommand>>execute
StDefineMissingEntityCommand>>execute
SpCommand(CmCommandDecorator)>>execute
[ specCommand execute ] in [ :specCommand |
			aButtonClass new
				label: specCommand name;
				help: specCommand description;
				in: [ :button |
					specCommand hasIcon
						ifTrue: [ button icon: specCommand icon ] ];
				action: [ specCommand execute ];
				yourself ] in SpCommand>>configureAsButtonOfClass: in Block: [ specCommand execute ]
FullBlockClosure(BlockClosure)>>cull:
SpToolbarButtonPresenter>>execute
SpToolbarButtonMorph(PluggableButtonMorph)>>performAction:
[:m |
		(m containsPoint: evt cursorPoint) ifTrue: [m enabled ifTrue: [ m performAction: evt ]]] in SpToolbarButtonMorph(PluggableButtonMorph)>>mouseUp: in Block: [:m |...
Array(SequenceableCollection)>>do:
SpToolbarButtonMorph(PluggableButtonMorph)>>mouseUp:
SpToolbarButtonMorph(Morph)>>handleMouseUp:
MouseButtonEvent>>sentTo:
SpToolbarButtonMorph(Morph)>>handleEvent:
SpToolbarButtonMorph(Morph)>>handleFocusEvent:
[
		result := focusHolder handleFocusEvent:
			(anEvent transformedBy: (focusHolder transformedFrom: self)).
	] in HandMorph>>sendFocusEvent:to:clear: in Block: [...
FullBlockClosure(BlockClosure)>>on:do:
WorldMorph>>becomeActiveDuring:
HandMorph>>sendFocusEvent:to:clear:
HandMorph>>sendEvent:focus:clear:
HandMorph>>sendMouseEvent:
HandMorph>>handleEvent:
[

		(morphicWorld activeHand isNotNil and: [ anEvent hand isNotNil ]) ifTrue: [
			morphicWorld activeHand handleEvent: anEvent
		]
	] in OSWindowMorphicEventHandler>>dispatchMorphicEvent: in Block: [...
WorldState>>runStepMethodsIn:
WorldMorph>>runStepMethods
WorldState>>doOneCycleNowFor:
WorldState>>doOneCycleFor:

**Comment by StevenCostiou** [comment]
Hi @tesonep, thanks.
I guess you mean `the protocol` in the title ;)
This is fixed in NewTools, and awaiting for an integration.
Maybe it already works on latest images.

**Comment by tesonep** [comment]
:D

**Comment by StevenCostiou** [comment]
Fixed by last merge
