### ISSUE TITLE
Running the test from StDebuggerTest package raise an Error 

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/NewTools#780]
this test method `testInspectingObjectWithPrintOnWithHaltOpenInspector` fails in P13. 

Pharo 13.0.0
Build information: Pharo-13.0.0+SNAPSHOT.build.93.sha.94bee0cce29d01cbf6ee2488e4eae47d5c426658 (64 Bit)

**Comment by matburnx** [comment]
The test doesn't fail anymore on `Pharo-13.0.0+SNAPSHOT.build.110.sha.c13ef42faa8e1568ccc21044dd61ce6b3a2e11fb`
