### ISSUE TITLE
 StSystemReporter breaks the build

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/NewTools#782]
UndeclaredVariableRead: Attempt to read undeclared variable StSystemReporter
UndeclaredVariable>>runtimeUndeclaredReadInContext:
[ :stream | StSystemReporter new reportImage: stream ] in SmalltalkCIPharo13(SmalltalkCIPharo9)>>imageInfo in Block: [ :stream | StSystemReporter new reportImage: [..]
String class(SequenceableCollection class)>>new:streamContents:
String class(SequenceableCollection class)>>streamContents:
SmalltalkCIPharo13(SmalltalkCIPharo9)>>imageInfo
[ SmalltalkCI printToStdout: self imageInfo ] in SmalltalkCIPharo13(SmalltalkCI)>>reportImageInfo in Block: [ SmalltalkCI printToStdout: self imageInfo ]
[ aBlock value ] in SmalltalkCIPharo13 class(SmalltalkCI class)>>fold:on:block: in Block: [ aBlock value ]
FullBlockClosure(BlockClosure)>>microsecondsToRun
FullBlockClosure(BlockClosure)>>millisecondsToRun
SmalltalkCIPharo13 class(SmalltalkCIPharo12 class)>>timeToRun:
SmalltalkCIPharo13 class(SmalltalkCI class)>>fold:on:block:
SmalltalkCIPharo13 class(SmalltalkCI class)>>fold:block:

**Comment by jecisc** [comment]
Seems fixed
