### ISSUE TITLE
The operations of the Debugger should have shortcuts.

### ISSUE THREAD

**Issue by tesonep** [pharo-spec/NewTools#83]

**Comment by guillep** [comment]
Please, at least `Proceed` :'(

**Comment by StevenCostiou** [comment]
So the key bindings are configured in the commands, but it is not clear why they do not work.
For example, `Proceed` should be `meta+r`. 
It does not work on my machine.
Under investigation.

**Comment by StevenCostiou** [comment]
So it is a bug in spec.
Workaround for now, we should fix this in spec.
Shortcuts are:

`meta+shift+o` = `stepOver`
`meta+shift+a` = `restart`
`meta+r` = `proceed`
`meta+e` = `stepInto`
`meta+shift+t`=`stepThrough`
