### ISSUE TITLE
[Debugger] Actual VS Expected view does not show the diff of line endings

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/NewTools#857]
I have a case where I assert that two strings are identical but the line endings are not.

The diff view is currently not able to show me this

![image](https://github.com/user-attachments/assets/641141b2-ce7c-4ccc-a3f9-e0cd19d3a5b0)

**Comment by StevenCostiou** [comment]
Could you provide a reproducible example?
I do not have the problem with line endings.

**Comment by StevenCostiou** [comment]
oh, ok, I tried with a cr and a lf and I have the pb

**Comment by StevenCostiou** [comment]
solved by https://github.com/pharo-spec/NewTools/pull/861
