### ISSUE TITLE
[Debugger] Add an inspect button to the Actual VS Expected view

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/NewTools#858]
I have a case where I assert that the result of two methods are identical. They return strings but they have different invisible characters. 

It would have helped we if I could have gotten an "inspect" button next to the Actual and Expected view doing a text diff at the bottom of the debugger

**Comment by StevenCostiou** [comment]
Following the debugger logic, I added the *expected* and *actual* objects in the inspector.
It pulls another bug in the updating of exceptions in the debugger.

![Capture d’écran 2024-10-11 à 11 16 38](https://github.com/user-attachments/assets/d9706aed-972c-42a5-973d-febc870ae645)

**Comment by jecisc** [comment]
Great thanks!
