### ISSUE TITLE
Creation of variables is wrong in the debugger

### ISSUE THREAD

**Issue by guillep** [pharo-spec/NewTools#86]
Pharo-9.0.0+build.580.sha.9514baad3830e43a539d94c24719b0317623995e (64 Bit)

The new debugger accepts to compile broken code now.
For example, code using variables that are not defined.

![image](https://user-images.githubusercontent.com/708322/89685622-fdd25680-d8fc-11ea-9470-0b43177da6f5.png)

When execution arrives to one of those points, there is the message `var is missing` and clicking the Create button proposes to create a class from it. However, sometimes I want an instance variable, or a temporary variable!

(also, I think I have no reproducible way yet, sometimes execution continues in the undeclared variable and does a `nil does not understand #xxx`. This happened to me compiling `SomeYetUnexistingClass new`. The code continued trying to execute the `#new`)

**Comment by StevenCostiou** [comment]
The debugger does not allow this anymore, and now asks to define undeclared variables when saving the modified code.
However, the execution seems to work with undeclared variables.
So it will never halt upon an undefined variable.
I need this issue to be fixed first: https://github.com/pharo-project/pharo/issues/7083

**Comment by MarcusDenker** [comment]
I think the original problem is fixed. I would close this issue.

Executing "SomeYetUnexistingClass new" on a Undeclared Variable SomeYetUnexistingClass is supposed to return nil and call new on that. 

I would close this issue.

**Comment by StevenCostiou** [comment]
We can close this one. Now compiling in the debugger does not allow undeclared variables.
