### ISSUE TITLE
Code in debug points commands identical to super class with no reason

### ISSUE THREAD

**Issue by StevenCostiou** [pharo-spec/NewTools#860]
`StDebugPointCommand>>canBeExecuted` returns `true`, just as the default `CmCommand` method.
Should be cleaned.

The release test `testNoEquivalentSuperclassMethods` should be updated accordingly.

**Comment by StevenCostiou** [comment]
Fixed by https://github.com/pharo-spec/NewTools/pull/854 that still have to be integrated.

**Comment by Ducasse** [comment]
#854 has been merged so I close this issue
