### ISSUE TITLE
Cmd + m seems too dumb

### ISSUE THREAD

**Issue by guillep** [pharo-spec/NewTools#87]
Pharo-9.0.0+build.580.sha.9514baad3830e43a539d94c24719b0317623995e (64 Bit)

When selecting an expression and doing Cmd+m, new tools use the entire selection as a selector. Before this tried to be a bit smarter, so we were able to look for implementors without selecting EXACTLY the selector.

![image](https://user-images.githubusercontent.com/708322/89685988-bbf5e000-d8fd-11ea-8feb-e3fef9f30989.png)

In the picture, I select `appendInstruction: anInstruction` and it is trying to look for implementors of that instead of just `appendInstruction:`.

**Comment by MarcusDenker** [comment]
this is fixed
