### ISSUE TITLE
lost code presenter actions after action system transition

### ISSUE THREAD

**Issue by estebanlm** [pharo-spec/NewTools#879]
For some reason, this actions where lost :(

**Comment by StevenCostiou** [comment]
@estebanlm the code commands are back and if we use the contextual menu, it works fine.
However shortcuts are now going through the old `RubSmalltalkEditor` code.

Example with the `printIt` action from the context menu:

![Capture d’écran 2024-11-08 à 15 08 53](https://github.com/user-attachments/assets/2d492594-4c16-4812-b16d-11a0ca3ab910)

Example with the `printIt` shortcut (`cmd+p` for me):

![Capture d’écran 2024-11-08 à 15 09 07](https://github.com/user-attachments/assets/8ecd57b3-5661-4e2c-b58e-c3d75f3e0e50)

**Comment by estebanlm** [comment]
ouch
