### ISSUE TITLE
The debugger should not let reordering the columns

### ISSUE THREAD

**Issue by guillep** [pharo-spec/NewTools#88]
Pharo-9.0.0+build.580.sha.9514baad3830e43a539d94c24719b0317623995e (64 Bit)

Right now, clicking in the debugger column headers reorders the stack, but I think this is pretty weird behaviour for a debugger. The alphabetical and reverse alphabetical order make no sense.

**Comment by StevenCostiou** [comment]
Good point.
This is a problem is spec: `SpStringTableColumn` implements a method `isSortable` that always returns `true`.
It needs an accessor with a default value set to `true`.

**Comment by StevenCostiou** [comment]
I will do the fix, but we'll wait that @estebanlm makes a new spec merge.

**Comment by StevenCostiou** [comment]
@estebanlm see commit https://github.com/pharo-spec/Spec/commit/0ee0e9823a4ef7215b53a84970b01c6dd639e026 
After that version of spec is merged, I will be able to make the modification in the debugger.

**Comment by StevenCostiou** [comment]
Fixed by https://github.com/pharo-project/pharo/pull/7255
