### ISSUE TITLE
Text commands (implementors, senders, etc.) do not recover properly selectors from text selection

### ISSUE THREAD

**Issue by StevenCostiou** [pharo-spec/NewTools#97]
Example 1:

` 1 between: 0 and: 10 `select everything and do `implementors`=> there is an error saying that *1 between: 0 and: 10* is not a selector instead of looking for implementors of *between:  and:*

That logic already exists in method `selectedSelectorWithRecursionDepth:` of `RubSmalltalkEditor` and should be extracted.

**Comment by MarcusDenker** [comment]
This should now work correctly
